In [22]:
import pandas as pd
import numpy as np
from faker import Faker
from datetime import datetime, timedelta
import random

fake = Faker('en_IN')

print("Quick Commerce Data Generation Started")

Quick Commerce Data Generation Started

In [23]:
# Number of records
NUM_ORDERS = 100000

# Indian cities
cities = [
    "Delhi",
    "Mumbai",
    "Bangalore",
    "Hyderabad",
    "Pune",
    "Chennai",
    "Kolkata",
    "Ahmedabad"
]

# Product categories
categories = [
    "Dairy",
    "Snacks",
    "Beverages",
    "Fruits",
    "Personal Care",
    "Frozen Food",
    "Household"
]

# Payment methods
payment_methods = [
    "UPI",
    "Card",
    "Cash on Delivery",
    "Wallet"
]

# Order status
order_statuses = [
    "Delivered",
    "Cancelled"
]

print("Master data created successfully")

Master data created successfully

In [24]:
# Generate realistic orders data

orders_data = []

for order_id in range(1, NUM_ORDERS + 1):

    city = random.choice(cities)

    # Peak hour simulation
    peak_hours = [8, 9, 10, 13, 14, 19, 20, 21]

    if random.random() < 0.7:
        hour = random.choice(peak_hours)
    else:
        hour = random.randint(0, 23)

    minute = random.randint(0, 59)

    order_time = datetime(
        2025,
        random.randint(1, 4),
        random.randint(1, 28),
        hour,
        minute
    )

    # Delivery duration
    delivery_minutes = max(10, int(np.random.normal(25, 8)))

    delivery_time = order_time + timedelta(minutes=delivery_minutes)

    # Cancellation probability
    if random.random() < 0.08:
        status = "Cancelled"
        delivery_time = None
    else:
        status = "Delivered"

    # Order values
    order_amount = round(random.uniform(100, 2500), 2)

    delivery_fee = round(random.uniform(10, 70), 2)

    discount = round(order_amount * random.uniform(0, 0.25), 2)

    final_amount = round(order_amount + delivery_fee - discount, 2)

    orders_data.append({
        "order_id": order_id,
        "city": city,
        "order_time": order_time,
        "delivery_time": delivery_time,
        "order_status": status,
        "payment_method": random.choice(payment_methods),
        "order_amount": order_amount,
        "delivery_fee": delivery_fee,
        "discount": discount,
        "final_amount": final_amount,
        "delivery_minutes": delivery_minutes
    })

print("Orders data generated successfully")

Orders data generated successfully

In [25]:
orders_df = pd.DataFrame(orders_data)

orders_df.head()

,order_id,city,order_time,delivery_time,order_status,payment_method,order_amount,delivery_fee,discount,final_amount,delivery_minutes
0,1,Hyderabad,2025-02-18 10:05:00,2025-02-18 10:28:00,Delivered,Cash on Delivery,1410.21,27.05,83.01,1354.25,23
1,2,Delhi,2025-02-17 14:29:00,2025-02-17 15:00:00,Delivered,Cash on Delivery,1514.24,17.65,19.65,1512.24,31
2,3,Pune,2025-01-27 05:02:00,2025-01-27 05:29:00,Delivered,Card,665.54,14.13,46.25,633.42,27
3,4,Kolkata,2025-01-26 13:08:00,2025-01-26 13:38:00,Delivered,Cash on Delivery,992.70,17.67,99.01,911.36,30
4,5,Ahmedabad,2025-04-20 08:04:00,2025-04-20 08:34:00,Delivered,UPI,766.43,33.26,42.39,757.30,30

In [26]:
# Extract business features

orders_df["order_hour"] = orders_df["order_time"].dt.hour

orders_df["order_day"] = orders_df["order_time"].dt.day_name()

orders_df["order_month"] = orders_df["order_time"].dt.month_name()

# Weekend flag
orders_df["is_weekend"] = orders_df["order_time"].dt.weekday >= 5

# Peak hour flag
peak_hours = [8, 9, 10, 13, 14, 19, 20, 21]

orders_df["is_peak_hour"] = orders_df["order_hour"].isin(peak_hours)

# Delivery SLA breach
orders_df["sla_breach"] = orders_df["delivery_minutes"] > 30

print("Feature engineering completed")

Feature engineering completed

In [27]:
orders_df.head()

,order_id,city,order_time,delivery_time,order_status,payment_method,order_amount,delivery_fee,discount,final_amount,delivery_minutes,order_hour,order_day,order_month,is_weekend,is_peak_hour,sla_breach
0,1,Hyderabad,2025-02-18 10:05:00,2025-02-18 10:28:00,Delivered,Cash on Delivery,1410.21,27.05,83.01,1354.25,23,10,Tuesday,February,False,True,False
1,2,Delhi,2025-02-17 14:29:00,2025-02-17 15:00:00,Delivered,Cash on Delivery,1514.24,17.65,19.65,1512.24,31,14,Monday,February,False,True,True
2,3,Pune,2025-01-27 05:02:00,2025-01-27 05:29:00,Delivered,Card,665.54,14.13,46.25,633.42,27,5,Monday,January,False,False,False
3,4,Kolkata,2025-01-26 13:08:00,2025-01-26 13:38:00,Delivered,Cash on Delivery,992.70,17.67,99.01,911.36,30,13,Sunday,January,True,True,False
4,5,Ahmedabad,2025-04-20 08:04:00,2025-04-20 08:34:00,Delivered,UPI,766.43,33.26,42.39,757.30,30,8,Sunday,April,True,True,False

In [28]:
orders_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 17 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   order_id          100000 non-null  int64
 1   city              100000 non-null  str
 2   order_time        100000 non-null  datetime64[us]
 3   delivery_time     91970 non-null   datetime64[us]
 4   order_status      100000 non-null  str
 5   payment_method    100000 non-null  str
 6   order_amount      100000 non-null  float64
 7   delivery_fee      100000 non-null  float64
 8   discount          100000 non-null  float64
 9   final_amount      100000 non-null  float64
 10  delivery_minutes  100000 non-null  int64
 11  order_hour        100000 non-null  int32
 12  order_day         100000 non-null  str
 13  order_month       100000 non-null  str
 14  is_weekend        100000 non-null  bool
 15  is_peak_hour      100000 non-null  bool
 16  sla_breach        100000 non-null  bool
dtypes: bool(3), datetime64[us](2), float64(4), int32(1), int64(2), str(5)
memory usage: 10.6 MB

In [29]:
orders_df.describe()

,order_id,order_time,delivery_time,order_amount,delivery_fee,discount,final_amount,delivery_minutes,order_hour
count,100000.000000,100000,91970,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,50000.500000,2025-03-01 00:27:29.952000,2025-03-01 00:12:10.284875,1298.002357,39.994024,161.711927,1176.284455,24.639410,13.466710
min,1.000000,2025-01-01 00:04:00,2025-01-01 00:30:00,100.040000,10.000000,0.000000,94.860000,10.000000,0.000000
25%,25000.750000,2025-01-28 23:43:00,2025-01-28 22:14:00,698.387500,24.990000,49.100000,646.537500,19.000000,9.000000
50%,50000.500000,2025-02-28 21:57:30,2025-02-28 22:02:00,1300.140000,40.060000,123.890000,1167.250000,25.000000,13.000000
75%,75000.250000,2025-03-28 20:36:00,2025-03-28 21:07:15,1897.250000,54.920000,244.210000,1690.352500,30.000000,19.000000
max,100000.000000,2025-04-28 23:55:00,2025-04-29 00:11:00,2499.970000,70.000000,622.680000,2547.620000,59.000000,23.000000
std,28867.657797,NaN,NaN,692.529666,17.306660,136.557751,616.012194,7.793832,5.681403

In [30]:
# Total orders
total_orders = len(orders_df)

# Total revenue
total_revenue = orders_df["final_amount"].sum()

# Average order value
avg_order_value = orders_df["final_amount"].mean()

# Cancellation rate
cancellation_rate = (
    orders_df["order_status"]
    .eq("Cancelled")
    .mean()
) * 100

print(f"Total Orders: {total_orders:,}")
print(f"Total Revenue: ₹{total_revenue:,.2f}")
print(f"Average Order Value: ₹{avg_order_value:.2f}")
print(f"Cancellation Rate: {cancellation_rate:.2f}%")

Total Orders: 100,000
Total Revenue: ₹117,628,445.47
Average Order Value: ₹1176.28
Cancellation Rate: 8.03%

In [31]:
city_performance = (
    orders_df
    .groupby("city")
    .agg({
        "order_id": "count",
        "final_amount": "sum",
        "delivery_minutes": "mean"
    })
    .reset_index()
)

city_performance.columns = [
    "city",
    "total_orders",
    "total_revenue",
    "avg_delivery_time"
]

city_performance.sort_values(
    by="total_revenue",
    ascending=False
)

        city  total_orders  total_revenue  avg_delivery_time
6     Mumbai         12628    14929901.96          24.655290
1  Bangalore         12666    14910400.26          24.612980
5    Kolkata         12590    14878088.63          24.713423
2    Chennai         12490    14677037.35          24.665492
7       Pune         12537    14672799.79          24.708862
3      Delhi         12391    14655746.17          24.579453
0  Ahmedabad         12371    14456601.18          24.601164
4  Hyderabad         12327    14447870.13          24.576296

In [33]:
# Save generated dataset

orders_df.to_csv(
    "../data/synthetic/quick_commerce_orders.csv",
    index=False
)

print("Dataset exported successfully")

Dataset exported successfully